stages:
  - build
  - release


build:
  stage: build
  image: cern/alma9-base:latest
  before_script:
    - yum install -y rpm-build python3 python3-devel git
  script:
    - |
      export CI_COMMIT_TAG=$(git describe --tags --abbrev=0)
      sed -i "s/Version:.*/Version:        $CI_COMMIT_TAG/" info-exporter.spec 
      mkdir -p rpmbuild/{SOURCES,SPECS,BUILD,RPMS,SRPMS}
      cp info-exporter.spec rpmbuild/SPECS/
      mkdir info-exporter-build
      cp info-exporter info-exporter-build/
      cp info-exporter-15s.service info-exporter-build/
      cp info-exporter-60s.service info-exporter-build/
      cp config-15s.json info-exporter-build/
      cp config-60s.json info-exporter-build/
      cp name_map_gen info-exporter-build/
      cp README.md info-exporter-build/
      cp request.json info-exporter-build/
      tar --create --file rpmbuild/SOURCES/info-exporter-$CI_COMMIT_TAG.tar.gz -C info-exporter-build .
      rpmbuild --define "_topdir `pwd`/rpmbuild" --target noarch -bb /builds/tgalpin/cables-info-exporter/rpmbuild/SPECS/info-exporter.spec
  artifacts:
    paths:
      - rpmbuild/RPMS/noarch/*.rpm
  only:
    - master
    - tags

release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  before_script: 
    - dnf install -y curl
  rules:
    - if: $CI_COMMIT_TAG                 # Run this job when a tag is created
  script:
    - |
      export RELEASE_TAG=$CI_COMMIT_TAG
      export PROJECT_ID=$CI_PROJECT_ID
      export TOKEN=$CI_JOB_TOKEN
      export API_URL="https://gitlab.com/api/v4/projects/$PROJECT_ID/releases"
      export ASSETS_PATH="rpmbuild/RPMS/noarch"

      # Create the release
      response=$(curl --header "PRIVATE-TOKEN: $TOKEN" --data "tag_name=$RELEASE_TAG" --data "description=Release $RELEASE_TAG" $API_URL)
      release_id=$(echo "$response" | jq '.id')

      # Upload assets to the release
      for file in $(ls $ASSETS_PATH/*.rpm); do
        echo "Uploading $file..."
        curl --header "PRIVATE-TOKEN: $TOKEN" -X POST --form "file=@$file" "$API_URL/$release_id/assets/links"
      done
  dependencies:
    - build
  release:                               # See https://docs.gitlab.com/ee/ci/yaml/#release for available properties
    tag_name: '$CI_COMMIT_TAG'
    description: 'Release $CI_COMMIT_TAG'

