stages:
  - build

build:
  stage: build
  image: cern/alma9-base:latest
  before_script:
    - yum install -y rpm-build python3 python3-devel git
  script:
   - sed -i "s/Version:.*/Version: $CI_COMMIT_TAG/" your_spec_file.spec 
    - mkdir -p rpmbuild/{SOURCES,SPECS,BUILD,RPMS,SRPMS}
    - cp info-exporter.spec rpmbuild/SPECS/
    - mkdir info-exporter-build
    - cp info-exporter info-exporter-build/
    - cp info-exporter-15s.service info-exporter-build/
    - cp info-exporter-60s.service info-exporter-build/
    - cp config-15s.json info-exporter-build/
    - cp config-60s.json info-exporter-build/
    - cp name_map_gen info-exporter-build/
    - cp README.md info-exporter-build/
    - cp request.json info-exporter-build/
    - tar --create --file rpmbuild/SOURCES/info-exporter-0.1.0.tar.gz -C info-exporter-build .
    - rpmbuild --define "_topdir `pwd`/rpmbuild" --target noarch -bb /builds/tgalpin/cables-info-exporter/rpmbuild/SPECS/info-exporter.spec
  artifacts:
    paths:
      - rpmbuild/RPMS/noarch/*.rpm
  only:
    - master
    - tags

